### ISSUE TITLE
Sign up to Community Events

### ISSUE THREAD

**Issue by guslong** [ERNICommunity/myCommunity#20]
As a user I want to sign up to a Community Event directly from within the app.

**Comment by drjazz2099** [comment]
Yo guys.

I implemented the REST Service call for this.

It looks like this:
GET:
http://mycommunity.nova.swisscloud.io/register/:eventId (id field)/:username

for example:
http://mycommunity.nova.swisscloud.io/register/556eb70de4b03c84a5d8b4b5/angus

(I can change the end point to a POST or a PUT if you like, but I think GET is ok for now, even if it is not strictly RESTful)

When the end point is called, the username is added to the a collection, called participants. The API will automatically ignore duplicates.

{
    "_id": {
        "$oid": "556eb70de4b03c84a5d8b4b5"
    },
    "title": "Hack and Hike",
    "type": "Hack Session",
    "participants": [
        "angus"
    ]
}

To display Participants to an event, please use the new participants field.

Happy hacking :-)

**Comment by drjazz2099** [comment]
When you call events:

http://mycommunity.nova.swisscloud.io/events

Please notice the extra participants field. If we use the login service to populate the user sign up "full users name". Then everything should be pretty robust.

**Comment by guslong** [comment]
Closed. Implemented by Ruel.
