### ISSUE TITLE
Add Connectivity plugin to iOS target

### ISSUE THREAD

**Issue by guslong** [ERNICommunity/myCommunity#22]
Implemented in Android but not yet in iOS

We use this plugin to check if there is an internet connection before first calling the backend.

Just need to add the NuGet Package Xam.Plugin.Connectivity to the iOS Target.

**Comment by guslong** [comment]
appears to have been done by Manila guys.

**Comment by rueldognidon-erni** [comment]
Hi gus, Yes.. I already added the connectivity plugin on IOS :)
