### ISSUE TITLE
Create a backend to provide details of community events via webservice

### ISSUE THREAD

**Issue by guslong** [ERNICommunity/myCommunity#6]
Iteration 1 can be "hard coded"
Iteration 2 allows editing of the data via a HTML administrator interface

**Comment by drjazz2099** [comment]
First version of API is up and running.

http://mycommunity.nova.swisscloud.io/events

Some times the first call is a bit slow. Probably the Swisscom cloud infrastructure kicking off the droplet. Will move this to a proper server soon.
