### ISSUE TITLE
Redesign the listview cells (as in new design)

### ISSUE THREAD

**Issue by guslong** [ERNICommunity/myCommunity#8]
Wilbert provided us with some nice graphics to use.
https://github.com/ERNICommunity/myCommunity/tree/master/Graphic%20design/icons
 Please orient the redesign to the screenshots shown in the readme.

**Comment by rueldognidon-erni** [comment]
Hi Gus, I had some spare time tonight and I'm still pumped up with the hacksession we did earlier here at ERNI PH. So I worked on this issue.

**Comment by drjazz2099** [comment]
Do you have any screen grabs of the details page? :-)

Curious now :-)

**Comment by guslong** [comment]
Hi Ruel
Great work. It looks really nice now. I like what you did and made everything in XAML. I was trying to figure that out myself for the ListView but wasn't quite getting it. Will study your code and learn something...
